databases:
  - name: morfesoft-db
    plan: free
    region: oregon

services:
  - type: web
    name: morfesoft
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn app:app
    healthCheckPath: /
    autoDeploy: true

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SQLALCHEMY_DATABASE_URI
        fromDatabase:
          name: morfesoft-db
          property: connectionString
      - key: TIMEZONE
        value: America/Santo_Domingo
      - key: PAYMENT_PROVIDER
        value: none
